[package]
name = "speech"
version = "0.1.0"
authors = ["mtyle"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio = { path = "../audio" }
deepspeech = "0.9.0"
